name: "Build docs"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.9' 
    - name: Install dependencies
      run: |
        pip install "numpydoc==1.1.0" "Sphinx==4.4.0"
    - name: Build docs
      run: sphinx-build docs docs/output
    - name: Deploy documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92 # This is version 4.1.4
      with:
        branch: gh-pages                     # The branch the action should deploy to.
        folder: docs/output                       # The folder the action should deploy.
        git-config-name: Deployment Bot      # Name of the committer
        git-config-email: deploy@github.com  # Email of the committer

